'use strict';
const $ = selector => document.querySelector(selector);
const projects = [
 {id:'linea',name:'Линеа',area:118,floors:1,rooms:3,features:['office','terrace'],image:'house-compact',label:'Один этаж. Больше свободы.',description:'Все важные пространства на одном уровне. Кабинет для спокойной работы и терраса для длинных летних вечеров.'},
 {id:'atria',name:'Атриа',area:168,floors:2,rooms:4,features:['office','terrace','guest'],image:'house-large',label:'Открытый характер',description:'Общая зона для встреч и приватные комнаты наверху. Панорамное остекление связывает интерьер с садом.'},
 {id:'nord',name:'Норд',area:142,floors:1,rooms:3,features:['terrace','guest'],image:'hero',label:'Ближе к природе',description:'Просторная гостиная с выходом в сад. Раздельные зоны для отдыха, гостей и личного времени.'},
 {id:'terra',name:'Терра',area:126,floors:1,rooms:3,features:['office'],image:'house-compact',label:'Собранный и спокойный',description:'Компактный сценарий загородной жизни с отдельным рабочим пространством и тремя спальнями.'},
 {id:'volume',name:'Волюм',area:206,floors:2,rooms:5,features:['office','terrace','guest'],image:'house-large',label:'Место для каждого',description:'Пять спален, место для гостей и отдельный кабинет. Дом, который вмещает большую семью и её планы.'},
 {id:'scene',name:'Сцена',area:176,floors:2,rooms:4,features:['terrace','guest'],image:'hero',label:'Жизнь с панорамой',description:'Четыре спальни и пространство для приёма гостей. Терраса продолжает общую зону на свежем воздухе.'},
];
let saved = new Set(); try{saved=new Set(JSON.parse(localStorage.getItem('forma-life-favorites')||'[]').filter(id=>projects.some(p=>p.id===id)))}catch{}
let compare=new Set(),onlySaved=false,configuration={facade:'stone',light:'day'},selection={project:null,package:null,scenario:null,facade:null,light:null};
const facadeNames={stone:'Светлый камень',wood:'Тёплое дерево',graphite:'Графит'};
const lightNames={day:'День',evening:'Вечер'};
let sceneApi=null,toastTimer;
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2600)}
function render(){
 const floor=$('#floorFilter').value,area=$('#areaFilter').value,feature=$('#featureFilter').value;
 const list=projects.filter(p=>(floor==='all'||p.floors===Number(floor))&&(area==='all'||area==='small'&&p.area<130||area==='medium'&&p.area>=130&&p.area<=180||area==='large'&&p.area>180)&&(feature==='all'||p.features.includes(feature))&&(!onlySaved||saved.has(p.id)));
 $('#resultCount').textContent=`Найдено: ${list.length} из ${projects.length}`; $('#savedCount').textContent=saved.size;$('#emptyState').hidden=list.length>0;
 $('#projectGrid').innerHTML=list.map(p=>`<article class="project-card"><div class="project-image"><button class="project-open" data-project="${p.id}" aria-label="Открыть проект ${p.name}"><img src="assets/${p.image}.webp" loading="lazy" alt="Демонстрационная архитектура проекта ${p.name}" width="800" height="600"></button><span class="project-label">${p.label}</span><button class="save-project" data-save="${p.id}" aria-label="${saved.has(p.id)?'Убрать из избранного':'Сохранить в избранное'}: ${p.name}" aria-pressed="${saved.has(p.id)}">${saved.has(p.id)?'♥':'♡'}</button></div><div class="project-title-row"><h3>${p.name}</h3><span>${p.area} м²</span></div><div class="project-spec"><span>${p.floors} ${p.floors===1?'этаж':'этажа'}</span><span>${p.rooms} ${p.rooms===5?'спален':'спальни'}</span><span>${p.features.includes('terrace')?'Терраса':'Кабинет'}</span></div><div class="project-buttons"><button class="project-open" data-project="${p.id}">Смотреть планировку <b>↗</b></button><button data-compare="${p.id}" aria-pressed="${compare.has(p.id)}">${compare.has(p.id)?'✓ В сравнении':'+ Сравнить'}</button></div></article>`).join('');
}
function updateCompare(){ $('#compareBar').hidden=!compare.size;$('#compareCount').textContent=compare.size }
function planSVG(p){const split=170+(p.area%30);return `<svg class="plan" viewBox="0 0 450 480" role="img" aria-label="Схематичная планировка первого этажа, не рабочий чертёж"><defs><pattern id="grid" width="20" height="20" patternUnits="userSpaceOnUse"><path d="M20 0H0V20" fill="none" stroke="#c8ccbd" stroke-width=".6"/></pattern></defs><rect width="450" height="480" fill="url(#grid)"/><g font-family="Golos,sans-serif" text-anchor="middle" fill="#344936"><text x="225" y="34" font-size="15">${p.name} / ${p.floors===2?'ПЕРВЫЙ ЭТАЖ':'СХЕМА ПРОСТРАНСТВ'}</text><rect x="48" y="83" width="354" height="302" fill="#f6f5ec" stroke="#344936" stroke-width="7"/><path d="M${split} 86V218M${split} 280V383M50 236H125M165 236H400M285 236V383" fill="none" stroke="#344936" stroke-width="5"/><path d="M180 80H275M400 125V195M95 385H155M325 385H373" stroke="#91a893" stroke-width="9"/><rect x="${split+18}" y="102" width="145" height="55" rx="3" fill="#dce1d1"/><rect x="${split+45}" y="176" width="78" height="30" rx="14" fill="#d1c0a5"/><rect x="65" y="104" width="60" height="74" fill="#ddd5c6"/><rect x="310" y="253" width="60" height="75" fill="#ddd5c6"/><text x="116" y="204" font-size="12">Кабинет</text><text x="289" y="224" font-size="12">Кухня-гостиная</text><text x="156" y="343" font-size="12">Холл</text><text x="342" y="349" font-size="12">Спальня</text><path d="M180 390V432H375V390" stroke="#acb59e" fill="none" stroke-width="2"/><text x="277" y="416" font-size="11">Терраса</text><text x="225" y="461" font-size="9" fill="#747e69">Схема зонирования · размеры и состав помещений уточняются при проектировании</text></g></svg>`}
function openProject(id){const p=projects.find(p=>p.id===id);$('#projectContent').innerHTML=`<div class="project-dialog-grid"><div class="modal-photo"><img src="assets/${p.image}.webp" alt="Проект ${p.name}">${planSVG(p)}</div><div class="modal-copy"><span class="eyebrow">Коллекция FORMA LIFE</span><h2>${p.name}</h2><p>${p.description}</p><div class="modal-spec"><span>${p.area} м²</span><span>${p.floors} ${p.floors===1?'этаж':'этажа'}</span><span>${p.rooms} ${p.rooms===5?'спален':'спальни'}</span></div><div class="plan-switch"><button data-tab="image" aria-pressed="true">Архитектура</button><button data-tab="plan" aria-pressed="false">Планировка</button></div><p class="small-note">Проект для предварительного подбора. Схема иллюстрирует распределение зон и уточняется вместе с архитектором. Стоимость — после привязки к участку.</p><button class="btn copper" data-select="${p.id}">Обсудить этот дом <span>↗</span></button><button class="text-link" data-go3d>Посмотреть 3D-эскиз Атриа <span>↗</span></button></div></div>`;$('#projectDialog').showModal()}
function syncSelection(){const parts=[];if(selection.project)parts.push(`Проект: ${selection.project}`);if(selection.package)parts.push(`Комплектация: ${selection.package}`);if(selection.scenario)parts.push(`Сценарий: ${selection.scenario}`);if(selection.facade)parts.push(`Фасад: ${selection.facade}`);if(selection.light)parts.push(`Освещение: ${selection.light}`);$('#selectionText').textContent=parts.join(' · ')||'Знакомство с коллекцией';$('#leadResult').hidden=true;$('#formError').textContent=''}
function goContact(){document.querySelectorAll('dialog[open]').forEach(d=>d.close());syncSelection();$('#contact').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});}
$('#projectGrid').addEventListener('click',e=>{
 const open=e.target.closest('[data-project]');if(open)return openProject(open.dataset.project);
 const save=e.target.closest('[data-save]');if(save){const id=save.dataset.save;saved.has(id)?saved.delete(id):saved.add(id);try{localStorage.setItem('forma-life-favorites',JSON.stringify([...saved]))}catch{}render();document.querySelector(`[data-save="${id}"]`)?.focus();return}
 const cmp=e.target.closest('[data-compare]');if(cmp){const id=cmp.dataset.compare;if(compare.has(id))compare.delete(id);else if(compare.size<3)compare.add(id);else return toast('Для сравнения выберите до трёх домов');render();updateCompare();document.querySelector(`[data-compare="${id}"]`)?.focus()}
});
$('#filterForm').addEventListener('change',render);$('#filterForm').addEventListener('submit',e=>e.preventDefault());$('#filterForm').addEventListener('reset',()=>{onlySaved=false;$('#savedOnly').setAttribute('aria-pressed','false');setTimeout(render,0)});
$('#savedOnly').onclick=()=>{onlySaved=!onlySaved;$('#savedOnly').setAttribute('aria-pressed',String(onlySaved));render()};
$('#clearCompare').onclick=()=>{compare.clear();updateCompare();render()};
$('#openCompare').onclick=()=>{const items=projects.filter(p=>compare.has(p.id));const row=(label,fn)=>`<tr><td>${label}</td>${items.map(p=>`<td>${fn(p)}</td>`).join('')}</tr>`;$('#comparison').innerHTML=`<div class="comparison-scroll"><table class="comparison-table"><caption class="small-note">Демонстрационные характеристики проектов</caption><thead><tr><th scope="col">Параметры</th>${items.map(p=>`<th scope="col">${p.name}</th>`).join('')}</tr></thead><tbody>${row('Площадь',p=>p.area+' м²')}${row('Этажность',p=>p.floors)}${row('Спальни',p=>p.rooms)}${row('Кабинет',p=>p.features.includes('office')?'Есть':'Не предусмотрен')}${row('Терраса',p=>p.features.includes('terrace')?'Есть':'Не предусмотрена')}${row('Стоимость',()=> 'После расчёта')}${row('Следующий шаг',p=>`<button data-select="${p.id}">Обсудить ${p.name} ↗</button>`)}</tbody></table></div>`;$('#compareDialog').showModal()};
$('.menu-toggle').onclick=()=>$('#navDialog').showModal();$('#navDialog').addEventListener('click',e=>{if(e.target.closest('a'))$('#navDialog').close()});
document.querySelectorAll('dialog').forEach(dialog=>{dialog.addEventListener('click',e=>{if(e.target.closest('[data-close]'))return dialog.close();if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}})});
document.addEventListener('click',e=>{
 const select=e.target.closest('[data-select]');if(select){const p=projects.find(p=>p.id===select.dataset.select);selection.project=p.name+' / '+p.area+' м²';selection.facade=null;selection.light=null;goContact()}
 const request=e.target.closest('[data-request]');if(request){selection.scenario=request.dataset.request;goContact()}
 const pack=e.target.closest('[data-package]');if(pack){selection.package=pack.dataset.package;goContact()}
 const tab=e.target.closest('[data-tab]');if(tab){$('.modal-photo').classList.toggle('plan-active',tab.dataset.tab==='plan');document.querySelectorAll('[data-tab]').forEach(t=>t.setAttribute('aria-pressed',String(t===tab)))}
 if(e.target.closest('[data-go3d]')){$('#projectDialog').close();$('#experience').scrollIntoView()}
});
document.querySelectorAll('[data-facade]').forEach(b=>b.onclick=()=>{configuration.facade=b.dataset.facade;document.querySelectorAll('[data-facade]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));sceneApi?.setFacade(configuration.facade)});
document.querySelectorAll('[data-light]').forEach(b=>b.onclick=()=>{configuration.light=b.dataset.light;document.querySelectorAll('[data-light]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));sceneApi?.setLight(configuration.light)});
$('#requestConfiguration').onclick=()=>{selection.project='Атриа / 168 м²';selection.facade=facadeNames[configuration.facade];selection.light=lightNames[configuration.light];goContact()};
$('#start3d').onclick=async()=>{const button=$('#start3d');button.disabled=true;$('#viewerStatus').textContent='Загружаем объёмную модель…';try{const {createHouseViewer}=await import('./viewer.js');sceneApi=createHouseViewer($('#viewer'),configuration);$('#viewerOverlay').hidden=true;$('#viewerFallback').hidden=true;$('#viewerBadge').hidden=false;$('#viewTools').hidden=false;$('#rotateLeft').onclick=()=>sceneApi.rotate(-.25);$('#rotateRight').onclick=()=>sceneApi.rotate(.25);$('#reset3d').onclick=()=>sceneApi.reset();}catch(err){button.disabled=false;$('#viewerStatus').textContent='3D недоступен на этом устройстве. Архитектуру можно посмотреть на изображении.';console.warn('3D fallback:',err.message)}};
$('#channel').onchange=()=>{const input=$('#leadForm').elements.contact;const tg=$('#channel').value==='Telegram';input.placeholder=tg?'@username или номер телефона':'+7 900 000-00-00';input.inputMode=tg?'text':'tel';input.setCustomValidity('')};
$('#leadForm').elements.contact.addEventListener('input',e=>e.target.setCustomValidity(''));
$('#leadForm').onsubmit=e=>{e.preventDefault();const f=e.currentTarget;const name=f.elements.name.value.trim(),contact=f.elements.contact.value.trim(),channel=f.elements.channel.value;const phone=/^\+?[\d\s()\-]{10,22}$/.test(contact)&&contact.replace(/\D/g,'').length>=10;const tg=channel==='Telegram'&&/^@[a-zA-Z][a-zA-Z0-9_]{4,31}$/.test(contact);if(!name){$('#formError').textContent='Укажите, пожалуйста, ваше имя.';f.elements.name.focus();return}if(!phone&&!tg){$('#formError').textContent=channel==='Telegram'?'Укажите номер телефона или Telegram в формате @username.':'Укажите телефон, включая код страны или города.';f.elements.contact.focus();return}$('#formError').textContent='';const box=$('#leadResult');box.replaceChildren();const h=document.createElement('h3');h.textContent='Обращение подготовлено';box.append(h);for(const text of [`${name} · ${contact}`,`${channel} · ${f.elements.time.value}`,$('#selectionText').textContent,f.elements.comment.value.trim(),'Это демонстрация: данные не отправлены. В рабочем сайте карточка обращения с проектом и пожеланиями передаётся ответственному специалисту.']){if(!text)continue;const p=document.createElement('p');p.textContent=text;box.append(p)}box.hidden=false;box.scrollIntoView({block:'nearest',behavior:'smooth'})};
render();
